# Project-wide Gradle settings
org.gradle.java.home=D:\\AppData\\Docker_claude_code\\INetSpeed\\.jdk\\jdk-17.0.13+11
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# Compose
android.defaults.buildfeatures.buildconfig=true
